from . import pick_lang

_TITLES: dict[str, dict[str, str]] = {
    "default": {"ru":"👨‍🏫 Нормальный учитель","en":"👨‍🏫 Normal teacher","uz":"👨‍🏫 Oddiy o‘qituvchi","kk":"👨‍🏫 Қалыпты мұғалім","de":"👨‍🏫 Normaler Lehrer","fr":"👨‍🏫 Prof normal","es":"👨‍🏫 Profesor normal","tr":"👨‍🏫 Normal öğretmen","ar":"👨‍🏫 معلّم عادي","hi":"👨‍🏫 सामान्य शिक्षक"},
    "simple": {"ru":"🧸 Объяснять по-простому","en":"🧸 Explain simply","uz":"🧸 Oddiy tilda","kk":"🧸 Қарапайым түсіндіру","de":"🧸 Einfach erklären","fr":"🧸 Simplement","es":"🧸 Explicar simple","tr":"🧸 Basit anlat","ar":"🧸 شرح مبسط","hi":"🧸 सरल समझाएँ"},
    "coach": {"ru":"🎯 Коучинг вопросами","en":"🎯 Coaching with questions","uz":"🎯 Savollar bilan","kk":"🎯 Сұрақпен жетелеу","de":"🎯 Coaching mit Fragen","fr":"🎯 Coaching par questions","es":"🎯 Coaching con preguntas","tr":"🎯 Sorularla koçluk","ar":"🎯 توجيه بالأسئلة","hi":"🎯 प्रश्नों से मार्गदर्शन"},
    "exam": {"ru":"📝 Экзаменатор","en":"📝 Examiner","uz":"📝 Imtihonchi","kk":"📝 Емтихан алушы","de":"📝 Prüfer","fr":"📝 Examinateur","es":"📝 Examinador","tr":"📝 Sınav modu","ar":"📝 ممتحِن","hi":"📝 परीक्षक"},
    "solve_full": {"ru":"📐 Решение задач с объяснением","en":"📐 Full solution with explanation","uz":"📐 To‘liq yechim","kk":"📐 Толық шешім","de":"📐 Vollständige Lösung","fr":"📐 Solution complète","es":"📐 Solución completa","tr":"📐 Tam çözüm","ar":"📐 حل كامل","hi":"📐 पूरा समाधान"},
    "hint": {"ru":"💡 Только подсказки","en":"💡 Hints only","uz":"💡 Faqat ishora","kk":"💡 Тек ишара","de":"💡 Nur Hinweise","fr":"💡 Indices seulement","es":"💡 Solo pistas","tr":"💡 Sadece ipucu","ar":"💡 تلميحات فقط","hi":"💡 केवल संकेत"},
    "check": {"ru":"✅ Проверка моего решения","en":"✅ Check my solution","uz":"✅ Yechimni tekshirish","kk":"✅ Шешімді тексеру","de":"✅ Lösung prüfen","fr":"✅ Vérifier ma solution","es":"✅ Revisar mi solución","tr":"✅ Çözümümü kontrol et","ar":"✅ تحقق من حلي","hi":"✅ मेरे समाधान की जाँच"},
    "notes": {"ru":"📓 Конспект по теме","en":"📓 Notes / summary","uz":"📓 Konspekt","kk":"📓 Конспект","de":"📓 Mitschrift","fr":"📓 Notes","es":"📓 Apuntes","tr":"📓 Notlar","ar":"📓 ملخص","hi":"📓 नोट्स"},
    "test": {"ru":"🧪 Генератор тестов","en":"🧪 Test generator","uz":"🧪 Test yaratish","kk":"🧪 Тест генераторы","de":"🧪 Test-Generator","fr":"🧪 Générateur de test","es":"🧪 Generador de test","tr":"🧪 Test üretici","ar":"🧪 مولّد اختبار","hi":"🧪 टेस्ट जनरेटर"},
    "cards": {"ru":"🎴 Карточки по теме","en":"🎴 Flashcards","uz":"🎴 Kartochkalar","kk":"🎴 Карточкалар","de":"🎴 Karteikarten","fr":"🎴 Fiches","es":"🎴 Tarjetas","tr":"🎴 Kartlar","ar":"🎴 بطاقات","hi":"🎴 फ्लैशकार्ड"},
    "cheatsheet": {"ru":"📌 Шпаргалка","en":"📌 Cheatsheet","uz":"📌 Shpargalka","kk":"📌 Шпаргалка","de":"📌 Spickzettel","fr":"📌 Fiche mémo","es":"📌 Chuleta","tr":"📌 Kopya kağıdı","ar":"📌 ملخص سريع","hi":"📌 चीट-शीट"},
    "mindmap": {"ru":"🧠 Mind-map по теме","en":"🧠 Mind map","uz":"🧠 Mind-map","kk":"🧠 Mind-map","de":"🧠 Mindmap","fr":"🧠 Carte mentale","es":"🧠 Mapa mental","tr":"🧠 Zihin haritası","ar":"🧠 خريطة ذهنية","hi":"🧠 माइंड मैप"},
    "study_plan": {"ru":"📅 Учебный план по теме","en":"📅 Study plan","uz":"📅 O‘quv rejasi","kk":"📅 Оқу жоспары","de":"📅 Lernplan","fr":"📅 Plan d’étude","es":"📅 Plan de estudio","tr":"📅 Çalışma planı","ar":"📅 خطة دراسة","hi":"📅 स्टडी प्लान"},
}

_DESCS: dict[str, dict[str, str]] = {
    "default": {"ru":"Структурные объяснения и аккуратный разбор.","en":"Structured explanations and clean solutions.","uz":"Tartibli tushuntirish va aniq yechim.","kk":"Құрылымды түсіндіру және нақты шешім.","de":"Strukturiert und verständlich.","fr":"Structuré et clair.","es":"Estructurado y claro.","tr":"Düzenli ve net.","ar":"منظم وواضح.","hi":"संरचित और स्पष्ट।"},
    "simple": {"ru":"Максимально просто, с примерами и короткими фразами.","en":"Very simple language, short sentences, analogies.","uz":"Juda sodda, qisqa gaplar va misollar.","kk":"Өте қарапайым, қысқа сөйлемдер.","de":"Sehr einfach, kurze Sätze, Beispiele.","fr":"Très simple, phrases courtes, exemples.","es":"Muy simple, frases cortas, ejemplos.","tr":"Çok basit, kısa cümleler, örnekler.","ar":"بسيط جدًا مع أمثلة قصيرة.","hi":"बहुत सरल, छोटे वाक्य, उदाहरण।"},
    "coach": {"ru":"Ведёт вопросами и подсказками, не выдаёт всё сразу.","en":"Guides with questions and hints first.","uz":"Avval savollar va ishoralar bilan yo‘naltiradi.","kk":"Алдымен сұрақ/ишарамен жетелейді.","de":"Leitet mit Fragen und Hinweisen.","fr":"Guide par questions et indices.","es":"Guía con preguntas y pistas.","tr":"Sorular ve ipuçlarıyla yönlendirir.","ar":"يرشد بأسئلة وتلميحات.","hi":"प्रश्नों और संकेतों से मार्गदर्शन।"},
    "exam": {"ru":"Проверочные вопросы и оценка понимания.","en":"Check questions and knowledge assessment.","uz":"Tekshiruv savollari va baholash.","kk":"Тексеру сұрақтары және бағалау.","de":"Prüffragen und Bewertung.","fr":"Questions de contrôle et évaluation.","es":"Preguntas de control y evaluación.","tr":"Kontrol soruları ve değerlendirme.","ar":"أسئلة تقييم وفحص.","hi":"जाँच प्रश्न और मूल्यांकन।"},
    "solve_full": {"ru":"Полный разбор: план, шаги, вычисления и итог.","en":"Full breakdown: plan, steps, calculations, result.","uz":"To‘liq yechim: reja, qadamlar, hisob, natija.","kk":"Толық шешім: жоспар, қадам, есептеу, қорытынды.","de":"Voll: Plan, Schritte, Rechnungen, Ergebnis.","fr":"Complet : plan, étapes, calculs, résultat.","es":"Completo: plan, pasos, cálculos, resultado.","tr":"Tam: plan, adımlar, hesap, sonuç.","ar":"كامل: خطة، خطوات، حسابات، نتيجة.","hi":"पूरा: योजना, स्टेप्स, गणना, उत्तर।"},
    "hint": {"ru":"Только направление и подсказки, без финального ответа.","en":"Only hints and direction, no final answer.","uz":"Faqat yo‘nalish va ishora, yakuniy javobsiz.","kk":"Тек бағыт пен ишара, соңғы жауапсыз.","de":"Nur Hinweise, kein Endergebnis.","fr":"Seulement des indices, pas de réponse finale.","es":"Solo pistas, sin respuesta final.","tr":"Sadece ipucu, final cevap yok.","ar":"تلميحات فقط بدون جواب نهائي.","hi":"केवल संकेत, अंतिम उत्तर नहीं।"},
    "check": {"ru":"Проверяет ваше решение и исправляет ошибки.","en":"Checks your solution and fixes mistakes.","uz":"Yechimingizni tekshiradi va xatoni ko‘rsatadi.","kk":"Шешімді тексеріп, қателерді түзетеді.","de":"Prüft deine Lösung und korrigiert.","fr":"Vérifie et corrige les erreurs.","es":"Revisa y corrige errores.","tr":"Kontrol eder, hataları düzeltir.","ar":"يتحقق ويصحح الأخطاء.","hi":"जाँचता है और गलतियाँ सुधारता है।"},
    "notes": {"ru":"Сделает конспект: определения, формулы, примеры.","en":"Creates structured notes with examples.","uz":"Konspekt: ta’riflar, formulalar, misollar.","kk":"Конспект: анықтама, формула, мысал.","de":"Mitschrift: Definitionen, Formeln, Beispiele.","fr":"Notes : définitions, formules, exemples.","es":"Apuntes: definiciones, fórmulas, ejemplos.","tr":"Notlar: tanım, formül, örnek.","ar":"ملخص: تعريفات، صيغ، أمثلة.","hi":"नोट्स: परिभाषाएँ, सूत्र, उदाहरण।"},
    "test": {"ru":"Сгенерирует тест и ответы с кратким разбором.","en":"Generates a quiz and explains answers briefly.","uz":"Test va qisqa izohli javoblar.","kk":"Тест және қысқа талдау.","de":"Quiz + kurze Erklärungen.","fr":"Test + corrections courtes.","es":"Test + corrección breve.","tr":"Test + kısa açıklama.","ar":"اختبار + شرح مختصر.","hi":"टेस्ट + संक्षिप्त व्याख्या।"},
    "cards": {"ru":"Карточки вопрос/ответ по теме.","en":"Flashcards: front/back.","uz":"Mavzu bo‘yicha kartalar: savol/javob.","kk":"Тақырып карточкалары: сұрақ/жауап.","de":"Karteikarten: Frage/Antwort.","fr":"Fiches: recto/verso.","es":"Tarjetas: pregunta/respuesta.","tr":"Kartlar: soru/cevap.","ar":"بطاقات: سؤال/جواب.","hi":"फ्लैशकार्ड: प्रश्न/उत्तर।"},
    "cheatsheet": {"ru":"Максимально кратко: формулы и тезисы.","en":"Ultra-compact key formulas and bullets.","uz":"Juda qisqa: formulalar va tezislar.","kk":"Өте қысқа: формула және тезис.","de":"Sehr kompakt: Formeln und Stichpunkte.","fr":"Très compact : formules et points clés.","es":"Muy compacto: fórmulas y puntos clave.","tr":"Çok kısa: formül ve maddeler.","ar":"مختصر جدًا: صيغ ونقاط.","hi":"बहुत संक्षिप्त: सूत्र और बिंदु।"},
    "mindmap": {"ru":"Текстовая mind-map с ветками и подветками.","en":"Text mind map with branches.","uz":"Tarmoqlar bilan matnli mind-map.","kk":"Тармақтары бар мәтін mind-map.","de":"Text-Mindmap mit Zweigen.","fr":"Carte mentale en texte.","es":"Mapa mental en texto.","tr":"Metin zihin haritası.","ar":"خريطة ذهنية نصية.","hi":"टेक्स्ट माइंड मैप।"},
    "study_plan": {"ru":"Учебный план по дням/неделям с практикой и проверкой.","en":"Day/week study plan with practice and checks.","uz":"Kun/hafta bo‘yicha reja: amaliyot va tekshiruv.","kk":"Күн/апта жоспары: тәжірибе және тексеру.","de":"Tages/Wochenplan mit Übung und Checks.","fr":"Plan par jours/semaines avec pratique.","es":"Plan por días/semanas con práctica.","tr":"Gün/hafta planı: pratik ve kontrol.","ar":"خطة يومية/أسبوعية مع تدريب.","hi":"दिन/सप्ताह स्टडी प्लान।"},
}

def mode_title(lang: str | None, mode: str) -> str:
    return pick_lang(lang, _TITLES.get(mode, _TITLES["default"]))

def mode_description(lang: str | None, mode: str) -> str:
    return pick_lang(lang, _DESCS.get(mode, _DESCS["default"]))
